import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "./components/layout/footer";
import Home from "./posts/page";
import Header from "./components/layout/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-slate-900">
      <body >
        <div className="bg-slate-900">
          <Header />
          <Home />
          <Footer />
        </div>
      </body>
    </html>
  );
}
